name: Deploy

on:
  push:
    tags:
      - 'v*'

env:
  PACKAGE_TOKEN: ${{secrets.PACKAGE_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.set_tag_name.outputs.tag_name }}
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install

      - name: Update package.json version
        id: set_tag_name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/v}  # 'v' 접두사 제거
          npm version $TAG_NAME --no-git-tag-version
          git config --global user.email "dev@hyper-cloud.kr"
          git config --global user.name "HypercloudDeployBot"
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Commit
        run: |
          git add package.json
          git commit -m "${GITHUB_REF#refs/tags/}"

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: npm publish --tag latest

      - name: Push changes
        run: git push origin HEAD:main
